import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarCheck, ShieldCheck, Scissors } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Hero() {
  return (
    <section id="home" className="relative min-h-[88vh] flex items-center py-16 overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-background to-accent/5" /><div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10"><div className="grid lg:grid-cols-2 gap-12 items-center"><div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700"><div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 rounded-full text-primary font-semibold text-sm"><ShieldCheck className="w-4 h-4" /> Verified barber booking workflow</div><h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold leading-tight">Choose a barber, pick an <span className="text-primary">available time</span>, and send your request.</h1><p className="text-lg sm:text-xl text-muted-foreground max-w-2xl">Trimlly helps customers browse barber services and request server-validated appointment slots while barbers keep control of their schedules.</p><div className="flex flex-col sm:flex-row gap-4"><Link href="/barbers"><Button size="lg" className="group text-base px-8 py-6">Browse Barbers <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" /></Button></Link><Link href="/login"><Button size="lg" variant="outline" className="text-base px-8 py-6 border-2">Create Account</Button></Link></div><div className="grid sm:grid-cols-3 gap-4 pt-4 text-sm"><div className="flex items-center gap-2"><CalendarCheck className="w-5 h-5 text-primary" />Available-slot validation</div><div className="flex items-center gap-2"><Scissors className="w-5 h-5 text-primary" />Service-based durations</div><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-primary" />Protected workspaces</div></div></div><div className="relative animate-in fade-in duration-700"><div className="relative rounded-3xl overflow-hidden shadow-2xl aspect-[4/3]"><Image src="/images/hero-salon.jpg" alt="Modern barber and salon interior" fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/30 to-transparent" /></div><div className="absolute -bottom-5 left-4 sm:-left-5 bg-card p-5 rounded-2xl shadow-xl border"><div className="font-semibold">Booking status stays clear</div><div className="text-sm text-muted-foreground">Pending → Confirmed → Completed</div></div></div></div></div></section>
  );
}
